### PR TITLE
Contour Counting Performance

### PR DESCRIPTION
**Pull request by scottsykora**
This adds some shortcuts to improve perfromance of the contour counting and the contour splitting algorithm.

@natep mind taking a look at this and testing it with your unit tests? It seemed to work in a few test cases but it's not super thorough.

I think this is also still too slow to not do some other improvements. The problem shapes we're working with still take 6 seconds or so to initially select. Thats an improvement from 60, but I think we would still want to do you 20-shape complexity bail-out.

### CODE REVIEW

**Comment by natep** [comment]
@scottsykora so the good news is, the unit tests do verify that your changes vastly speed up the contour counting. Both of the problem shapes are now down to about 5 seconds each.

However, the code change is also changing the results of the contour calculations for a few shapes:

```
XCTAssertEqual failed: ("1") is not equal to ("2") - Patterns_44 has calculated wrong number of contours
XCTAssertEqual failed: ("3") is not equal to ("2") - Botanical_39 has calculated wrong number of contours
XCTAssertEqual failed: ("64") is not equal to ("59") - Patterns_24 has calculated wrong number of contours
XCTAssertEqual failed: ("192") is not equal to ("191") - Patterns_5 has calculated wrong number of contours
```

That first entry is one of the problem shapes, and its value has changed in a way that affects whether it is splittable. Now maybe that's ok, and that shape really shouldn't be splittable anyway. I'm not sure.

**Comment by scottsykora** [comment]
@natep so I've updated the patterns pack and it now actually only shows 1 contour for both the problem shapes we had before. Looking closely at the shape I *think* this is the right result.

Also, looking at what I think is botanicals 39... it seems like that should only have 1 shape in it. (that is the s shape below right?)

IMG_D52E27CFCA40-1

Patterns 5 also seems *more* correct now, since 192 is divisible by three (64 * 3) and that shape is 64 groups of three shapes.

IMG_A9152ED63D92-1

**Comment by natep** [comment]
I can confirm that is Botanical_39.

**Comment by scottsykora** [comment]
@natep where do we stand with this one? Should we merge this into master on this repo?

**Comment by natep** [comment]
@scottsykora I'm fine with merging it in. You may want to create a PR in Assembly that pulls in this change, and see if it causes the new unit tests to fail. If so, we may need to tweak them (or maybe just regen the cached contour data they use).

**Review by natep — APPROVED** [review]

**Pull request merged**
